CREATE TABLE `consultations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`patient_id` integer NOT NULL,
	`date` integer NOT NULL,
	`reason` text NOT NULL,
	`symptoms` text,
	`blood_pressure` text,
	`heart_rate` integer,
	`temperature` text,
	`weight` text,
	`height` text,
	`physical_exam` text,
	`diagnosis` text NOT NULL,
	`treatment` text,
	`prescription` text,
	`lab_requested` integer DEFAULT false,
	`rx_requested` integer DEFAULT false,
	`ecg_requested` integer DEFAULT false,
	`ultrasound_requested` integer DEFAULT false,
	`other_studies` text,
	`next_appointment` text,
	`notes` text,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`patient_id`) REFERENCES `patients`(`id`) ON UPDATE no action ON DELETE no action
);
